user_sql = {
    "getUserByTel": "select user_id,user_nickname,user_phone,user_icon,user_skin,user_sex,user_age,user_autograpgh,user_fans,user_watchs from user where user_phone={telephone} limit 1",
    "commonRegister": "insert into user(user_phone,user_password,user_nickname,regist_date) values('{telephone}','{password}','{nickname}',{data})",
    "getPassword": "select user_password from user where user_phone={telephone} limit 1",
    "getUserById": "select user_id,user_nickname,user_phone,user_icon,user_skin,user_sex,user_age,user_autograpgh,user_fans,user_watchs from user where user_id={user_id} limit 1",
    "getUserByName": "select user_id from user where user_nickname='{name}' limit 1",
    "myDynamics": "SELECT d.id,d.words,d.click,d.dynamic_images,d.cols,d.cots,d.fbs,d.tags,d.user_id,d.data,'nothing' as new_col,'dynamic' as t_name from dynamic d WHERE (user_id) in (SELECT other_id from follow WHERE user_id={user_id}) union ALL SELECT j.id,j.title,j.click,j.images,j.cols,j.cots,j.fbs,j.tags,j.user_id,j.data,j.words as new_col,'journal' as t_name from journal j WHERE (user_id) in (SELECT other_id from follow WHERE user_id={user_id}) UNION ALL SELECT c.id,c.title,c.click,c.img,c.cols,c.cots,c.fbs,c.tags,c.user_id ,c.data,GROUP_CONCAT(s.title SEPARATOR '&') as new_col,'test' as t_name from commodity_test_main c LEFT JOIN commodity_test_subtitle s on c.id=s.main_id  WHERE (user_id) in (SELECT other_id from follow WHERE user_id={user_id})  GROUP BY c.title union ALL SELECT d.id,d.words,d.click,d.dynamic_images,d.cols,d.cots,d.fbs,d.tags,d.user_id,d.data,'nothing' as new_col,'dynamic' as t_name from dynamic d WHERE user_id={user_id} union ALL SELECT j.id,j.title,j.click,j.images,j.cols,j.cots,j.fbs,j.tags,j.user_id,j.data,j.words as new_col,'journal' as t_name from journal j WHERE user_id={user_id} UNION ALL SELECT c.id,c.title,c.click,c.img,c.cols,c.cots,c.fbs,c.tags,c.user_id ,c.data,GROUP_CONCAT(s.title SEPARATOR '&') as new_col,'test' as t_name from commodity_test_main c LEFT JOIN commodity_test_subtitle s on c.id=s.main_id WHERE user_id={user_id}  GROUP BY c.title ORDER BY data DESC",
    "mineDy": "SELECT d.id,d.words,d.click,d.dynamic_images,d.cols,d.cots,d.fbs,d.tags,d.user_id,d.data,'nothing' as new_col,'dynamic' as t_name from dynamic d WHERE user_id={user_id} union ALL SELECT j.id,j.title,j.click,j.images,j.cols,j.cots,j.fbs,j.tags,j.user_id,j.data,j.words as new_col,'journal' as t_name from journal j WHERE user_id={user_id} UNION ALL SELECT c.id,c.title,c.click,c.img,c.cols,c.cots,c.fbs,c.tags,c.user_id ,c.data,GROUP_CONCAT(s.title SEPARATOR '&') as new_col,'test' as t_name from commodity_test_main c LEFT JOIN commodity_test_subtitle s on c.id=s.main_id WHERE user_id={user_id}  GROUP BY c.title ORDER BY data DESC",
    "getDyById": "SELECT * from {tb} WHERE id={id}",
    "getTestById": "SELECT c.id,c.title,c.content,c.click,c.img,c.cols,c.cots,c.fbs,c.tags,c.user_id ,c.data,GROUP_CONCAT(s.title SEPARATOR '&') as a_title,GROUP_CONCAT(s.content SEPARATOR '&') as a_content from commodity_test_main c LEFT JOIN commodity_test_subtitle s on c.id=s.main_id  WHERE c.id={id}",
    "updateClick": "UPDATE {tp} SET {tp}.click={tp}.click+1 WHERE id={id}",
    "updateUserMessage": "UPDATE user set user_nickname='{user_nickname}',user_phone='{user_phone}',user_sex={user_sex},user_age={user_age},user_autograpgh='{user_autograpgh}' WHERE `user`.user_id={user_id}",
    "applicationForResidence": "",
    "celebrityCertification": "",
    "skinTest": "",
    "deleteDynamics": "",
    "updateDynamics": "",
    "selectMyDynamics": "",
    "mineCollections": "SELECT a.id,a.words,a.click,a.dynamic_images,a.cols,a.cots,a.fbs,a.tags,a.user_id,a.data,'nothing' as new_col,'dynamic' as t_name from   dynamic a  LEFT JOIN (SELECT id from dynamic_collection GROUP BY id) as b  on  a.id =b.id WHERE a.id in (SELECT d.dynamic_id from dynamic_collection d LEFT JOIN `user` u on d.user_id = u.user_id WHERE u.user_id={id}) UNION ALL SELECT j.id,j.title,j.click,j.images,j.cols,j.cots,j.fbs,j.tags,j.user_id,j.data,j.words as new_col,'journal' as t_name from journal j LEFT JOIN (SELECT id from journal_collection GROUP BY id) as b on j.id=b.id WHERE j.id in (SELECT j1.journal_id from journal_collection j1 LEFT JOIN `user` u on j1.user_id = u.user_id WHERE u.user_id={id}) UNION ALL SELECT c.id,c.title,c.click,c.img,c.cols,c.cots,c.fbs,c.tags,c.user_id ,c.data,GROUP_CONCAT(s.title SEPARATOR '&') as new_col,'test' as t_name from commodity_test_main c LEFT JOIN commodity_test_subtitle s on c.id=s.main_id  WHERE (c.id) in (SELECT t.test_id FROM test_collection t LEFT JOIN `user` u on t.user_id=u.user_id WHERE u.user_id={id}) GROUP BY c.title",
    "increaseCollection": "INSERT into {tp}_collection VALUES (null,{user_id},{other_id},{data});",
    "deleteCollection": "DELETE from {tp}_collection WHERE user_id={user_id} and {tp}_id={other_id};",
    "viewCollections": "SELECT id from {tp}_collection WHERE user_id={user_id} and {tp}_id={other_id};",
    "updateCollection1": "UPDATE `user` SET user_cols=user_cols+1 where user_id={user_id};",
    "updateCollection11": "UPDATE {tp} SET cols=cols+1 where id={id};",
    "updateCollection0": "UPDATE `user` SET user_cols=user_cols-1 where user_id={user_id};",
    "updateCollection00": "UPDATE {tp} SET cols=cols-1 where id={id};",
    "increaseCompliment": "INSERT into {tp}_fabulous VALUES (null,{user_id},{other_id},{data});",
    "deleteCompliment": "DELETE from {tp}_fabulous WHERE user_id={user_id} and {tp}_id={other_id};",
    "viewCompliment": "SELECT id from {tp}_fabulous WHERE user_id={user_id} and {tp}_id={other_id};",
    "updateCompliment1": "UPDATE `user` SET user_fbs=user_fbs+1 where user_id={user_id};",
    "updateCompliment11": "UPDATE {tp} SET fbs=fbs+1 where id={id};",
    "updateCompliment0": "UPDATE `user` SET user_fbs=user_fbs-1 where user_id={user_id};",
    "updateCompliment00": "UPDATE {tp} SET fbs=fbs-1 where id={id};",
    "increaseConcerns": "INSERT into follow VALUES (null,{user_id},{other_id},{data})",
    "deleteConcerns": "DELETE from follow WHERE user_id={user_id} and other_id={other_id}",
    "viewConcerns": "SELECT id from follow WHERE user_id={user_id} and other_id={other_id}",
    "increaseComment": "INSERT into {type}_comment VALUES (null,'{content}',{other_id},{user_id},{data})",
    "deleteComment": "",
    "viewComment": "SELECT {type}_comment.* from  {type}_comment LEFT JOIN  {tp}  on {type}_comment.{type}_id={tp}.id WHERE {tp}.id={id}",
    "updateComment1": "UPDATE {tp} SET {tp}.cots={tp}.cots+1 WHERE {tp}.id={other_id}",
    "updateComment11": "UPDATE `user` SET `user`.user_cots=`user`.user_cots+1 WHERE `user`.user_id={user_id}",
    "updateComment0": "",
    "updateComment00": "",
    "addTimeCosmetics": ""
}
